version: "3.8"

services:
  microservice:
    build: .
    volumes:
      - ./:/app
    env_file:
      - .env
    networks:
      - rabbitmq-network
    restart: always

networks:
  rabbitmq-network:
    external: true